data1 <- read.table("c:/Users/Durga/Desktop/household_power_consumption.txt",header = TRUE,sep = ";", stringsAsFactors = FALSE)
data1$Date <- as.Date(data1$Date,"%d/%m/%Y")
data3 <- subset.data.frame(data1,data1$Date>= as.Date("2007-02-01") & data1$Date <= as.Date("2007-02-02"))
datetime <- strptime(paste(data3$Date,data3$Time), "%Y-%m-%d %H:%M:%S") 
data3$Sub_metering_1 <- as.numeric(data3$Sub_metering_1)
data3$Sub_metering_2 <- as.numeric(data3$Sub_metering_2)
data3$Sub_metering_3 <- as.numeric(data3$Sub_metering_3)
png("plot3.png",width=480,height=480)
plot(datetime,data3$Sub_metering_1,type="l", ylab="Energy Submetering", xlab="")
lines(datetime,data3$Sub_metering_2,type="l",col="red")
lines(datetime,data3$Sub_metering_3,type="l",col="blue")
legend("topright",c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),lty=1,lwd=2.5,col=c("black","red","blue"))
dev.off()
